# Bakes a PNG/JPG/BMP/GIF into a compiled-in Tauraro RGBA pixel module,
# directly modeled on scripts/bake-font.ps1 -- same reasoning applies here
# verbatim: Tauraro's stdlib has no image-decoder support at all, and a
# real PNG/JPEG decoder (inflate, Huffman, IDCT, ...) is a large, risky
# undertaking to write from scratch and get correct on the freestanding
# tiers, which have no filesystem to load an image file from at runtime
# anyway. A baked pixel array turns "draw an image" into a plain per-pixel
# blit at paint time: no decoder, no float dependency, identical and
# equally safe on every backend, because it is just data.
#
#   .\scripts\bake-image.ps1 -ImagePath assets\logo.png -Name logo -OutTr .nebula\assets\image_logo.tr
#
# Output shape (one module per baked image, named after -Name so an app
# with several images gets one file per image, no collisions):
#   pub def <name>_w() -> int
#   pub def <name>_h() -> int
#   pub def <name>_pixels() -> List[u8]     # RGBA, 4 bytes/pixel, row-major
#
# Kept intentionally simple (RGBA/GDI+ GetPixel, no LockBits) to match
# bake-font.ps1's own style -- fine for the icon/logo-sized assets this is
# meant for; a multi-megapixel photo would produce an enormous .tr source
# file, same tradeoff the font atlas already accepts for the same reason.

param(
    [Parameter(Mandatory=$true)]
    [string]$ImagePath,
    [Parameter(Mandatory=$true)]
    [string]$Name,
    [string]$OutTr = "",
    [string]$PreviewPng = "",
    # 0 = no resize, keep the source image's native pixel size.
    [int]$MaxW = 0,
    [int]$MaxH = 0
)

$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.Drawing

if (-not (Test-Path $ImagePath)) { throw "no such image file: $ImagePath" }
if ($OutTr -eq "") { $OutTr = "toolkit\assets\image_$Name.tr" }

$src = New-Object -TypeName System.Drawing.Bitmap -ArgumentList (Resolve-Path $ImagePath).Path
Write-Host "loaded image: $($src.Width) x $($src.Height)"

$w = $src.Width
$h = $src.Height
$bmp = $src
$resized = $false
if (($MaxW -gt 0 -and $w -gt $MaxW) -or ($MaxH -gt 0 -and $h -gt $MaxH)) {
    $scaleW = if ($MaxW -gt 0) { [double]$MaxW / $w } else { 1.0 }
    $scaleH = if ($MaxH -gt 0) { [double]$MaxH / $h } else { 1.0 }
    $scale = [math]::Min($scaleW, $scaleH)
    $w = [math]::Max(1, [int][math]::Round($w * $scale))
    $h = [math]::Max(1, [int][math]::Round($h * $scale))
    $bmp = New-Object -TypeName System.Drawing.Bitmap -ArgumentList $w, $h
    $gfx = [System.Drawing.Graphics]::FromImage($bmp)
    $gfx.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
    $gfx.DrawImage($src, 0, 0, $w, $h)
    $gfx.Dispose()
    $resized = $true
    Write-Host "resized to: $w x $h"
}

# --- Walk pixels, RGBA row-major ---------------------------------------------

$pixelBytes = New-Object 'System.Collections.Generic.List[byte]'  # w*h*4 bytes
for ($y = 0; $y -lt $h; $y++) {
    for ($x = 0; $x -lt $w; $x++) {
        $px = $bmp.GetPixel($x, $y)
        $pixelBytes.Add([byte]$px.R)
        $pixelBytes.Add([byte]$px.G)
        $pixelBytes.Add([byte]$px.B)
        $pixelBytes.Add([byte]$px.A)
    }
}

if ($PreviewPng -ne "") {
    New-Item -ItemType Directory -Force (Split-Path $PreviewPng) | Out-Null
    try {
        $bmp.Save($PreviewPng, [System.Drawing.Imaging.ImageFormat]::Png)
        Write-Host "wrote preview: $PreviewPng"
    } catch {
        Write-Host "WARNING: preview PNG save failed ($($_.Exception.Message)) -- continuing without it"
    }
}

if ($resized) { $bmp.Dispose() }
$src.Dispose()

# --- Emit the Tauraro module --------------------------------------------------

$sb = New-Object System.Text.StringBuilder
[void]$sb.Append("# GENERATED by scripts/bake-image.ps1 from $ImagePath -- do not hand-edit.`n")
[void]$sb.Append("#`n")
[void]$sb.Append("# RGBA, 4 bytes/pixel, row-major: byte offset = (row * w + col) * 4.`n")
[void]$sb.Append("`n")
[void]$sb.Append("pub def $($Name)_w() -> int:`n    return $w`n`n")
[void]$sb.Append("pub def $($Name)_h() -> int:`n    return $h`n`n")
[void]$sb.Append("pub def $($Name)_pixels() -> List[u8]:`n    return [")

for ($i = 0; $i -lt $pixelBytes.Count; $i++) {
    if ($i -gt 0) { [void]$sb.Append(", ") }
    [void]$sb.Append("$($pixelBytes[$i]) as u8")
}
[void]$sb.Append("]`n")

New-Item -ItemType Directory -Force (Split-Path $OutTr) | Out-Null
[System.IO.File]::WriteAllText((Join-Path (Get-Location) $OutTr), $sb.ToString())

Write-Host ""
Write-Host "wrote $OutTr" -ForegroundColor Green
Write-Host "  $($pixelBytes.Count) bytes, ${w}x${h} RGBA"
